version: '3.8'
services:
  database:
    image: postgis/postgis:15-3.3-alpine
    container_name: atac-database
    environment:
      POSTGRES_DB: atac_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s 
  backend:
    container_name: atac-server
    build: ./atac-server
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgres://root:root@database:5432/atac_db
    depends_on:
      database:
        condition: service_healthy
    restart: always
    volumes:
      - ./atac-server:/usr/src/atac-server
    command: sh -c "npm run migrate && npm run start"
  frontend:
    container_name: atac-web
    build: ./atac-web
    ports:
      - 3000:3000
    volumes:
      - ./atac-web:/usr/src/atac-web
    restart: always
    depends_on:
      - backend
volumes:
  db-volume: